#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$DIR/lib/bootstrap.sh"

#########################################
# SWIGGITY SWITHUB, WE RELEASIN ON GITHUB
#########################################

usage() {
	echo "
Usage: swiggity [subcommand]
	Requires a git repository
	Ensure you have GITHUB_ACCESS_TOKEN env var set.

	Sub commands:
	  - describe
	    Describes the release. This will be the body of the github release.
	  - push <org_name/repo_name>
	    * Renames old production branch to blue, and branches HEAD to new production branch
	    * _Force pushes_ these branches to your repository
	    * Creates a release tag, which is pushed
	    * Submits a release to github, using your GITHUB_ACCESS_TOKEN, containing the changelog between blue/production

	.swiggityrc can contain:
	  - BLUE_BRANCH
	    The name of the branch to use for 'blue'
	  - GREEN_BRANCH
	    The name of the branch to use for 'green'
	  - REPO_NAME
	    The <org_name/repo_name> to push releases to.
"
}

main() {
	set -eo pipefail; [[ "$TRACE" ]] && set -x
	case "$1" in
		push)       create-release {$REPO_NAME:-$2} $(change-log $BLUE_BRANCH $GREEN_BRANCH);;
		*)          usage;;
	esac
}

main "$@"
